### ISSUE TITLE
content type is "text/plain; charset=utf8"

### ISSUE THREAD

**Issue by tom-on-the-internet** [petaki/inertia-go#2]
Apologies in advance if this is not related to the inertia-go module, which is great.

This module does not set the content-type to "text/html". I believe it relies on Go's behaviour of reading the first number of bytes and determining the content type based on that.

Locally this works fine for me and I get content-type "text/html; charset=utf8". But when I run this in an AWS Lambda function, the content type is "text/plain; charset=utf8". The browser then does not render the html.

As a workround, I've wrapped the `Render` method.

```
func (s *Server) renderInertia(w http.ResponseWriter, r *http.Request, component string, props map[string]interface{}) error {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")

	return s.inertiaManager.Render(w, r, component, props)
}
```

This works because the content-type is overwritten for JSON responses, but this solution feels pretty bad.

Do you have any insight into why "text/plain; charset=utf8" is being set as the content-type?
Would it make sense to explicitly set the content-type in this module if no `x-inertia` header exists?

Thanks for your time!

**Comment by petaki** [comment]
@tom-on-the-internet Thanks for the info and solution idea!

Can you try with the `w.Header().Set("Content-Type", "text/html")` (without the charset)?

I don't want to force the charset.

**Comment by petaki** [comment]
@tom-on-the-internet I added explicit html content type without charset.

Please reopen the ticket if it doesn't work.
